import { createMiddleware } from '@tanstack/react-start';

// Dev-only guard for a TanStack Start dev-server bug. When the browser calls a
// server function whose id is stale — the extracted server-fn modules were
// regenerated by HMR while editing, or a window-refocus react-query refetch
// hits a still-cached client bundle — the dev resolver imports the module and
// returns `mod[export]`, which is now `undefined`. `handleServerAction` then
// crashes reading `action.method`, surfacing as a noisy unhandled 500 in the
// server console. We catch that exact crash and return a clean 404 so the
// browser simply refetches against the fresh bundle. Remove once upstream
// resolves an unknown server-fn id gracefully.
export const devStaleServerFnGuardMiddleware = createMiddleware({
  type: 'request',
}).server(async ({ next }) => {
  if (process.env.NODE_ENV === 'production') {
    return next();
  }
  try {
    return await next();
  } catch (error) {
    const isStaleServerFnCrash =
      error instanceof TypeError &&
      error.message.includes("reading 'method'") &&
      (error.stack?.includes('handleServerAction') ?? false);
    if (isStaleServerFnCrash) {
      return new Response('Stale server function reference; reload the page.', {
        status: 404,
      });
    }
    throw error;
  }
});
