import * as icons from '@fortawesome/free-solid-svg-icons';

import type { CategoryIconDef } from './categoryIcons';

export const categoryIconsOther = [
  { value: 'globe', icon: icons.faGlobe },
  { value: 'seedling', icon: icons.faSeedling },
  { value: 'piggy-bank', icon: icons.faPiggyBank },
  { value: 'dollar-sign', icon: icons.faDollarSign },
  { value: 'chart-line', icon: icons.faChartLine },
  { value: 'fire-extinguisher', icon: icons.faFireExtinguisher },
  { value: 'mobile-screen', icon: icons.faMobileScreen },
  { value: 'screwdriver-wrench', icon: icons.faScrewdriverWrench },
  { value: 'brush', icon: icons.faBrush },
  { value: 'palette', icon: icons.faPalette },
  { value: 'bolt', icon: icons.faBolt },
  { value: 'film', icon: icons.faFilm },
  { value: 'trash', icon: icons.faTrash },
  { value: 'ghost', icon: icons.faGhost },
  { value: 'toilet-paper', icon: icons.faToiletPaper },
  { value: 'money-bill', icon: icons.faMoneyBill },
  { value: 'people-group', icon: icons.faPeopleArrows },
  { value: 'music', icon: icons.faMusic },
  { value: 'square-plus', icon: icons.faPlusSquare },
  { value: 'tooth', icon: icons.faTooth },
  { value: 'box-archive', icon: icons.faBoxArchive },
  { value: 'vials', icon: icons.faVials },
  { value: 'filter', icon: icons.faFilter },
  { value: 'robot', icon: icons.faRobot },
  { value: 'lock', icon: icons.faLock },
  { value: 'key', icon: icons.faKey },
  { value: 'shield', icon: icons.faShieldAlt },
  { value: 'user-group', icon: icons.faUserFriends },
  { value: 'dumbbell', icon: icons.faDumbbell },
  { value: 'person-running', icon: icons.faRunning },
  { value: 'futbol', icon: icons.faFutbol },
  { value: 'sun', icon: icons.faSun },
  { value: 'moon', icon: icons.faMoon },
] as const satisfies readonly CategoryIconDef[];
