/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavingsSpendingsRouteImport } from './routes/savings-spendings'
import { Route as BudgetingRouteImport } from './routes/budgeting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavingsSpendingsIndexRouteImport } from './routes/savings-spendings.index'
import { Route as SettingsSubscriptionsRouteImport } from './routes/settings.subscriptions'
import { Route as SettingsSourcesRouteImport } from './routes/settings.sources'
import { Route as SettingsCategoriesRouteImport } from './routes/settings.categories'
import { Route as SavingsSpendingsArchiveRouteImport } from './routes/savings-spendings.archive'
import { Route as SettingsSubscriptionsIndexRouteImport } from './routes/settings.subscriptions.index'
import { Route as SettingsSubscriptionsArchiveRouteImport } from './routes/settings.subscriptions.archive'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsSpendingsRoute = SavingsSpendingsRouteImport.update({
  id: '/savings-spendings',
  path: '/savings-spendings',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingRoute = BudgetingRouteImport.update({
  id: '/budgeting',
  path: '/budgeting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsSpendingsIndexRoute = SavingsSpendingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SavingsSpendingsRoute,
} as any)
const SettingsSubscriptionsRoute = SettingsSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourcesRoute = SettingsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SavingsSpendingsArchiveRoute = SavingsSpendingsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SavingsSpendingsRoute,
} as any)
const SettingsSubscriptionsIndexRoute =
  SettingsSubscriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsSubscriptionsRoute,
  } as any)
const SettingsSubscriptionsArchiveRoute =
  SettingsSubscriptionsArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => SettingsSubscriptionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgeting': typeof BudgetingRoute
  '/savings-spendings': typeof SavingsSpendingsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/transactions': typeof TransactionsRoute
  '/savings-spendings/archive': typeof SavingsSpendingsArchiveRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsRouteWithChildren
  '/savings-spendings/': typeof SavingsSpendingsIndexRoute
  '/settings/subscriptions/archive': typeof SettingsSubscriptionsArchiveRoute
  '/settings/subscriptions/': typeof SettingsSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgeting': typeof BudgetingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/transactions': typeof TransactionsRoute
  '/savings-spendings/archive': typeof SavingsSpendingsArchiveRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/savings-spendings': typeof SavingsSpendingsIndexRoute
  '/settings/subscriptions/archive': typeof SettingsSubscriptionsArchiveRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budgeting': typeof BudgetingRoute
  '/savings-spendings': typeof SavingsSpendingsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/transactions': typeof TransactionsRoute
  '/savings-spendings/archive': typeof SavingsSpendingsArchiveRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/settings/subscriptions': typeof SettingsSubscriptionsRouteWithChildren
  '/savings-spendings/': typeof SavingsSpendingsIndexRoute
  '/settings/subscriptions/archive': typeof SettingsSubscriptionsArchiveRoute
  '/settings/subscriptions/': typeof SettingsSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgeting'
    | '/savings-spendings'
    | '/settings'
    | '/statistics'
    | '/transactions'
    | '/savings-spendings/archive'
    | '/settings/categories'
    | '/settings/sources'
    | '/settings/subscriptions'
    | '/savings-spendings/'
    | '/settings/subscriptions/archive'
    | '/settings/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgeting'
    | '/settings'
    | '/statistics'
    | '/transactions'
    | '/savings-spendings/archive'
    | '/settings/categories'
    | '/settings/sources'
    | '/savings-spendings'
    | '/settings/subscriptions/archive'
    | '/settings/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/budgeting'
    | '/savings-spendings'
    | '/settings'
    | '/statistics'
    | '/transactions'
    | '/savings-spendings/archive'
    | '/settings/categories'
    | '/settings/sources'
    | '/settings/subscriptions'
    | '/savings-spendings/'
    | '/settings/subscriptions/archive'
    | '/settings/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetingRoute: typeof BudgetingRoute
  SavingsSpendingsRoute: typeof SavingsSpendingsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-spendings': {
      id: '/savings-spendings'
      path: '/savings-spendings'
      fullPath: '/savings-spendings'
      preLoaderRoute: typeof SavingsSpendingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting': {
      id: '/budgeting'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof BudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings-spendings/': {
      id: '/savings-spendings/'
      path: '/'
      fullPath: '/savings-spendings/'
      preLoaderRoute: typeof SavingsSpendingsIndexRouteImport
      parentRoute: typeof SavingsSpendingsRoute
    }
    '/settings/subscriptions': {
      id: '/settings/subscriptions'
      path: '/subscriptions'
      fullPath: '/settings/subscriptions'
      preLoaderRoute: typeof SettingsSubscriptionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sources': {
      id: '/settings/sources'
      path: '/sources'
      fullPath: '/settings/sources'
      preLoaderRoute: typeof SettingsSourcesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/savings-spendings/archive': {
      id: '/savings-spendings/archive'
      path: '/archive'
      fullPath: '/savings-spendings/archive'
      preLoaderRoute: typeof SavingsSpendingsArchiveRouteImport
      parentRoute: typeof SavingsSpendingsRoute
    }
    '/settings/subscriptions/': {
      id: '/settings/subscriptions/'
      path: '/'
      fullPath: '/settings/subscriptions/'
      preLoaderRoute: typeof SettingsSubscriptionsIndexRouteImport
      parentRoute: typeof SettingsSubscriptionsRoute
    }
    '/settings/subscriptions/archive': {
      id: '/settings/subscriptions/archive'
      path: '/archive'
      fullPath: '/settings/subscriptions/archive'
      preLoaderRoute: typeof SettingsSubscriptionsArchiveRouteImport
      parentRoute: typeof SettingsSubscriptionsRoute
    }
  }
}

interface SavingsSpendingsRouteChildren {
  SavingsSpendingsArchiveRoute: typeof SavingsSpendingsArchiveRoute
  SavingsSpendingsIndexRoute: typeof SavingsSpendingsIndexRoute
}

const SavingsSpendingsRouteChildren: SavingsSpendingsRouteChildren = {
  SavingsSpendingsArchiveRoute: SavingsSpendingsArchiveRoute,
  SavingsSpendingsIndexRoute: SavingsSpendingsIndexRoute,
}

const SavingsSpendingsRouteWithChildren =
  SavingsSpendingsRoute._addFileChildren(SavingsSpendingsRouteChildren)

interface SettingsSubscriptionsRouteChildren {
  SettingsSubscriptionsArchiveRoute: typeof SettingsSubscriptionsArchiveRoute
  SettingsSubscriptionsIndexRoute: typeof SettingsSubscriptionsIndexRoute
}

const SettingsSubscriptionsRouteChildren: SettingsSubscriptionsRouteChildren = {
  SettingsSubscriptionsArchiveRoute: SettingsSubscriptionsArchiveRoute,
  SettingsSubscriptionsIndexRoute: SettingsSubscriptionsIndexRoute,
}

const SettingsSubscriptionsRouteWithChildren =
  SettingsSubscriptionsRoute._addFileChildren(
    SettingsSubscriptionsRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsSourcesRoute: typeof SettingsSourcesRoute
  SettingsSubscriptionsRoute: typeof SettingsSubscriptionsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsSourcesRoute: SettingsSourcesRoute,
  SettingsSubscriptionsRoute: SettingsSubscriptionsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetingRoute: BudgetingRoute,
  SavingsSpendingsRoute: SavingsSpendingsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
